export enum APP_MODULES {
  USERS = 'USERS',
  USER_AREA = 'USER_AREA',
  USER_LEVELS = 'USER_LEVELS',
  USER_POSITION = 'USER_POSITION',
  USER_ROLES = 'USER_ROLES',
  TENANT = 'TENANT',
  FILES = 'FILES',
  SERVICES = 'SERVICES',
  INVOICES = 'INVOICES',
  FAQ = 'FAQ',
}


